import type { Metadata } from 'next';
import { Recursive } from 'next/font/google';
import './globals.css';
import { Navbar } from '@/components/navbar';
import { Provider } from '@/components/providers';
import Footer from '@/components/footer';

const recursive = Recursive({
  subsets: ['latin'],
  weight: ['300', '400', '500', '600', '700', '800', '900'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`bg-slate-100 text-slate-900 dark:bg-slate-900 dark:text-slate-100 ${recursive.className}`}
      >
        <Provider>
          <Navbar />
          <main className="flex flex-col min-h-[calc(100vh-3.5rem-1px)]">
            {children}
          </main>

          <Footer />
        </Provider>
      </body>
    </html>
  );
}
